# Change baseurl before deploy
#baseurl = "https://zongyanglaobiao.github.io/hugo-blog"
paginate = 5
title = "J.A"
# Change it to your Disqus shortname before using
disqusShortname = "hugo-theme-stack"
buildFuture = true
