# Change baseurl before deploy
baseurl = "https://zongyanglaobiao.github.io"
pagination.pagerSize = 6
title = "J.A"
# Change it to your Disqus shortname before using
disqusShortname = "hugo-theme-stack"
# 解决因为时间不渲染文章问题
buildFuture = true