# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/zongyanglaobiao"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://x.com/james_aks_"

[social.params]
icon = "brand-twitter"

[[social]]
identifier = "csdn"
name = "CSDN"
url = "https://blog.csdn.net/m0_64332518?spm=1000.2115.3001.5343"

[social.params]
icon = "csdn"
