name: 部署博客
on:
  push:
    branches:
      - master
jobs:
  deploy-hugo-blog:
    name: 开始部署
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:

      - name: 设置hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.128.2'
          extended: true

      - name: 编译
        uses: actions/checkout@v4
        run: |
          go version
          hugo version